query ($userName: String) {
  MediaListCollection (userName: $userName, type: ANIME) {
    lists {
      entries {
        id
        mediaId
        status
        score
        notes
        progress
        repeat
        updatedAt
        startedAt {year month day}
        completedAt {year month day}
        media {
          idMal
          season
          seasonYear
          genres
          tags {
            name
            rank
            isMediaSpoiler
          }
          studios {
            edges {
              node {
                name
                isAnimationStudio
              }
            }
          }
          title {
            romaji
            english
            native
            userPreferred
          }
          format
          status
          description
          startDate {year month day}
          endDate {year month day}
          episodes
          averageScore
        }
      }
    }
  }
}