name: Create Release
on:
  push:
    tags:
      - v*
jobs:
  linux-build:
    name: Linux Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
      - name: Download binaries
        run: |
          wget https://github.com/ffbinaries/ffbinaries-prebuilt/releases/download/v4.2.1/ffprobe-4.2.1-linux-64.zip -O ffprobe.zip
          sudo apt-get install mpv unzip
          sudo mv /usr/bin/mpv distribute/
          unzip ffprobe.zip
          mv ffprobe distribute/
      - name: Run pyinstaller
        run: pyinstaller --distpath dist/linux -y distribute/linux.spec
      - name: Copy scripts into distribution path
        run: cp distribute/finish-setup.sh distribute/anitracker.desktop dist/linux/
      - name: Replace version in desktop file
        run: sed -i "s/Version=.*/Version=$(grep '__version__ = ' anitracker/__init__.py | cut -d\" -f 2)/" dist/linux/anitracker.desktop
      - name: Create tarball
        run: |
          cd dist/linux/
          tar czf ../anitracker.tar.gz ./*
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: anitracker.tar.gz
          path: dist/anitracker.tar.gz
          if-no-files-found: error
  windows-build:
    name: Windows Build
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
      - name: Download MPV
        uses: suisei-cn/actions-download-file@v1
        id: mpv
        with:
          url: https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20210801-git-416668d.7z/download
      - name: Download ffprobe
        uses: suisei-cn/actions-download-file@v1
        id: ffprobe
        with:
          url: https://github.com/ffbinaries/ffbinaries-prebuilt/releases/download/v4.2.1/ffprobe-4.2.1-win-64.zip
      - name: Prepare binaries
        run: |
          7z x ${{ steps.mpv.outputs.filename }}
          7z x ${{ steps.ffprobe.outputs.filename }}
          move ffprobe.exe distribute 
          move mpv.exe distribute
          move mpv.com distribute
      - name: Run pyinstaller
        run: pyinstaller distribute\windows.spec --distpath=dist\windows -y
      - name: Create zip
        run: 7z a "AniTracker.7z" "dist\windows" -r
      - name: Upload zip
        uses: actions/upload-artifact@v2
        with:
          name: AniTracker.7z
          path: AniTracker.7z
          if-no-files-found: error
  make-windows-installer:
    name: Make Windows Installer
    runs-on: ubuntu-latest
    needs: [windows-build]
    steps:
      - uses: actions/checkout@v2
      - name: Download makensis
        run: |
          sudo apt-get update
          sudo apt-get install -y nsis
      - name: Download FindProc plugin
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: https://nsis.sourceforge.io/mediawiki/images/3/3c/FindProc.zip
          file-name: findproc_plugin.zip
          location: ${{ github.workspace }}
      - name: Extract FindProc plugin
        run: sudo 7z x -o"/usr/share/nsis/Plugins/x86-ansi/" "${{ github.workspace }}/findproc_plugin.zip"
      - name: Download zip
        uses: actions/download-artifact@v2
        with:
          name: AniTracker.7z
      - name: Unzip
        run: |
          7z x "AniTracker.7z"
          find dist/ -type d -exec chmod 755 {} \;
          find dist/ -type f -exec chmod 644 {} \;
      - name: Create nsis installer
        run: |
          ls -lah
          ls -lah dist
          ls -lah dist/windows/
          makensis distribute/anitracker.nsis
      - uses: actions/upload-artifact@v2
        with:
          name: AniTracker.exe
          path: dist/AniTracker.exe
          if-no-files-found: error
  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [linux-build, make-windows-installer]
    steps:
      - uses: actions/download-artifact@v2
      - name: Create Release
        uses: ncipollo/release-action@v1.8.6
        with:
          draft: true
          artifacts: "anitracker.tar.gz,AniTracker.exe"
          token: ${{ secrets.GITHUB_TOKEN }}
